<a href="https://colab.research.google.com/github/prodipsarkar03/Learning-Purpose-with-Subin/blob/main/4_Implemantion_multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
dataset=pd.read_csv("house_price_data.csv")

In [ ]:
print(dataset)

       Size_sqft  Bedrooms        Age          Price
0    1649.014246  2.171005  23.784943  264543.181412
1    1458.520710  2.439819  15.389173  227614.933109
2    1694.306561  3.747294  24.348030  280019.801924
3    1956.908957  3.610370  26.778189  341819.988798
4    1429.753988  2.979098  22.067175  237042.476300
..           ...       ...        ...            ...
295  1292.127121  2.489984  23.243549  215906.624265
296  1769.879963  2.730125  19.164410  282808.284264
297  1592.189856  2.021236  20.733568  259723.856154
298  1743.858636  2.555707  26.032545  278597.873012
299  1688.888653  3.377300  15.915322  306431.450594

[300 rows x 4 columns]


In [ ]:
x=dataset.iloc[:,:-1 ].values
y=dataset.iloc[:,:-1 ].values
print(x)
print(y)

[[1.64901425e+03 2.17100499e+00 2.37849431e+01]
 [1.45852071e+03 2.43981896e+00 1.53891734e+01]
 [1.69430656e+03 3.74729361e+00 2.43480296e+01]
 [1.95690896e+03 3.61037027e+00 2.67781893e+01]
 [1.42975399e+03 2.97909841e+00 2.20671745e+01]
 [1.42975891e+03 3.11732738e+00 2.93839791e+01]
 [1.97376384e+03 4.27766490e+00 1.61310540e+01]
 [1.73023042e+03 2.40842861e+00 1.37767265e+01]
 [1.35915768e+03 3.54709738e+00 1.11063988e+01]
 [1.66276801e+03 2.79780735e+00 2.74802216e+01]
 [1.36097469e+03 2.78231880e+00 2.32718283e+01]
 [1.36028107e+03 4.09877685e+00 1.97220766e+01]
 [1.57258868e+03 3.82541635e+00 2.13998431e+01]
 [9.26015927e+02 3.81350964e+00 1.43725548e+01]
 [9.82524650e+02 4.30547881e+00 3.22287599e+01]
 [1.33131374e+03 3.02100384e+00 2.06461059e+01]
 [1.19615066e+03 3.68195297e+00 2.05469740e+01]
 [1.59427420e+03 2.68973324e+00 2.36288331e+01]
 [1.22759278e+03 3.32416635e+00 2.24050462e+01]
 [1.07630889e+03 2.86985695e+00 2.11194201e+01]
 [1.93969463e+03 3.09699596e+00 1.604762

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x)

[[1.64901425e+03 2.17100499e+00 2.37849431e+01]
 [1.45852071e+03 2.43981896e+00 1.53891734e+01]
 [1.69430656e+03 3.74729361e+00 2.43480296e+01]
 [1.95690896e+03 3.61037027e+00 2.67781893e+01]
 [1.42975399e+03 2.97909841e+00 2.20671745e+01]
 [1.42975891e+03 3.11732738e+00 2.93839791e+01]
 [1.97376384e+03 4.27766490e+00 1.61310540e+01]
 [1.73023042e+03 2.40842861e+00 1.37767265e+01]
 [1.35915768e+03 3.54709738e+00 1.11063988e+01]
 [1.66276801e+03 2.79780735e+00 2.74802216e+01]
 [1.36097469e+03 2.78231880e+00 2.32718283e+01]
 [1.36028107e+03 4.09877685e+00 1.97220766e+01]
 [1.57258868e+03 3.82541635e+00 2.13998431e+01]
 [9.26015927e+02 3.81350964e+00 1.43725548e+01]
 [9.82524650e+02 4.30547881e+00 3.22287599e+01]
 [1.33131374e+03 3.02100384e+00 2.06461059e+01]
 [1.19615066e+03 3.68195297e+00 2.05469740e+01]
 [1.59427420e+03 2.68973324e+00 2.36288331e+01]
 [1.22759278e+03 3.32416635e+00 2.24050462e+01]
 [1.07630889e+03 2.86985695e+00 2.11194201e+01]
 [1.93969463e+03 3.09699596e+00 1.604762

In [ ]:
print(x_test)

[[1.65451431e+03 3.04852163e+00 2.62787806e+01]
 [1.24596188e+03 4.68714164e+00 1.96491714e+01]
 [1.57258868e+03 3.82541635e+00 2.13998431e+01]
 [9.39820442e+02 3.54336019e+00 2.70467372e+01]
 [1.75573000e+03 2.42310813e+00 1.89300558e+01]
 [1.26502401e+03 4.62861555e+00 2.12801487e+01]
 [1.28089001e+03 3.63859246e+00 1.32777474e+01]
 [1.65451058e+03 2.40760608e+00 2.11106689e+01]
 [1.29692340e+03 3.85765962e+00 1.86555565e+01]
 [1.57726512e+03 3.12029563e+00 9.59035296e+00]
 [1.43756332e+03 3.07156624e+00 2.41024109e+01]
 [1.33131374e+03 3.02100384e+00 2.06461059e+01]
 [1.43296116e+03 2.24364925e+00 2.27989522e+01]
 [2.02963627e+03 3.37114587e+00 1.68113001e+01]
 [1.52025846e+03 2.18177932e+00 2.94101225e+01]
 [7.14076469e+02 5.15318246e+00 1.29624415e+01]
 [1.93238199e+03 3.01841838e+00 1.91152639e+01]
 [1.52912326e+03 2.10158533e+00 1.81951692e+01]
 [1.70387932e+03 2.09568337e+00 1.85910770e+01]
 [1.78901284e+03 2.88767195e+00 2.57463666e+01]
 [1.36604551e+03 2.99202736e+00 2.214809

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=regressor.predict(x_test)
print(y_pred)

[[1.65451431e+03 3.04852163e+00 2.62787806e+01]
 [1.24596188e+03 4.68714164e+00 1.96491714e+01]
 [1.57258868e+03 3.82541635e+00 2.13998431e+01]
 [9.39820442e+02 3.54336019e+00 2.70467372e+01]
 [1.75573000e+03 2.42310813e+00 1.89300558e+01]
 [1.26502401e+03 4.62861555e+00 2.12801487e+01]
 [1.28089001e+03 3.63859246e+00 1.32777474e+01]
 [1.65451058e+03 2.40760608e+00 2.11106689e+01]
 [1.29692340e+03 3.85765962e+00 1.86555565e+01]
 [1.57726512e+03 3.12029563e+00 9.59035296e+00]
 [1.43756332e+03 3.07156624e+00 2.41024109e+01]
 [1.33131374e+03 3.02100384e+00 2.06461059e+01]
 [1.43296116e+03 2.24364925e+00 2.27989522e+01]
 [2.02963627e+03 3.37114587e+00 1.68113001e+01]
 [1.52025846e+03 2.18177932e+00 2.94101225e+01]
 [7.14076469e+02 5.15318246e+00 1.29624415e+01]
 [1.93238199e+03 3.01841838e+00 1.91152639e+01]
 [1.52912326e+03 2.10158533e+00 1.81951692e+01]
 [1.70387932e+03 2.09568337e+00 1.85910770e+01]
 [1.78901284e+03 2.88767195e+00 2.57463666e+01]
 [1.36604551e+03 2.99202736e+00 2.214809

In [ ]:
print(y_test)
print(y_pred)

[[1.65451431e+03 3.04852163e+00 2.62787806e+01]
 [1.24596188e+03 4.68714164e+00 1.96491714e+01]
 [1.57258868e+03 3.82541635e+00 2.13998431e+01]
 [9.39820442e+02 3.54336019e+00 2.70467372e+01]
 [1.75573000e+03 2.42310813e+00 1.89300558e+01]
 [1.26502401e+03 4.62861555e+00 2.12801487e+01]
 [1.28089001e+03 3.63859246e+00 1.32777474e+01]
 [1.65451058e+03 2.40760608e+00 2.11106689e+01]
 [1.29692340e+03 3.85765962e+00 1.86555565e+01]
 [1.57726512e+03 3.12029563e+00 9.59035296e+00]
 [1.43756332e+03 3.07156624e+00 2.41024109e+01]
 [1.33131374e+03 3.02100384e+00 2.06461059e+01]
 [1.43296116e+03 2.24364925e+00 2.27989522e+01]
 [2.02963627e+03 3.37114587e+00 1.68113001e+01]
 [1.52025846e+03 2.18177932e+00 2.94101225e+01]
 [7.14076469e+02 5.15318246e+00 1.29624415e+01]
 [1.93238199e+03 3.01841838e+00 1.91152639e+01]
 [1.52912326e+03 2.10158533e+00 1.81951692e+01]
 [1.70387932e+03 2.09568337e+00 1.85910770e+01]
 [1.78901284e+03 2.88767195e+00 2.57463666e+01]
 [1.36604551e+03 2.99202736e+00 2.214809

In [ ]:
score=regressor.score(x_test,y_test)
print(score*100,'%')

100.0 %
